2021-06-14 21:40:50,818 - ERROR - weibo.py[:179] - list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 174, in main
    correntRank = parseHTMLByXPath(content)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 80, in parseHTMLByXPath
    titles = [title.strip() for title in titles[0, 11]]
TypeError: list indices must be integers or slices, not tuple
2021-06-14 21:43:36,774 - ERROR - weibo.py[:179] - list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 174, in main
    correntRank = parseHTMLByXPath(content)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 80, in parseHTMLByXPath
    titles = [title.strip() for title in titles][0, 10]
TypeError: list indices must be integers or slices, not tuple
2021-06-14 21:45:01,186 - ERROR - weibo.py[:179] - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 174, in main
    correntRank = parseHTMLByXPath(content)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 86, in parseHTMLByXPath
    correntRank[title] = {'href': hrefs[i], 'hot': hots[i]}
TypeError: 'int' object is not subscriptable
2021-06-14 21:48:06,991 - ERROR - weibo.py[:180] - string indices must be integers
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 175, in main
    correntRank = parseHTMLByXPath(content)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 76, in parseHTMLByXPath
    titles = html.xpath('//tr[position()>1]/td[@class="td-02"]/a[not(contains(@href, "javascript:void(0);"))]/text()'[0,10])
TypeError: string indices must be integers
2021-06-14 21:49:04,981 - ERROR - weibo.py[:180] - list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 175, in main
    correntRank = parseHTMLByXPath(content)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 76, in parseHTMLByXPath
    titles = html.xpath('//tr[position()>1]/td[@class="td-02"]/a[not(contains(@href, "javascript:void(0);"))]/text()')[0,10]
TypeError: list indices must be integers or slices, not tuple
2021-06-14 21:51:24,624 - ERROR - weibo.py[:181] - 'list' object has no attribute 'subList'
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 176, in main
    correntRank = parseHTMLByXPath(content)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 77, in parseHTMLByXPath
    titles = titles.subList(0, 10)
AttributeError: 'list' object has no attribute 'subList'
2021-06-15 12:34:57,674 - ERROR - weibo.py[:179] - unhashable type: 'slice'
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 175, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 119, in updateJSON
    print(rank[0:10])
TypeError: unhashable type: 'slice'
2021-06-15 12:35:03,057 - ERROR - weibo.py[:179] - (0, 10)
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 175, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 119, in updateJSON
    print(rank[0, 10])
KeyError: (0, 10)
2021-06-15 12:37:03,647 - ERROR - weibo.py[:179] - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 176, in main
    rankMD = updateArchive(rankJSON)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 134, in updateArchive
    lines = [line.format(title=k, hot=v['hot'], href=v['href']) for k, v in rank.items()]
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 134, in <listcomp>
    lines = [line.format(title=k, hot=v['hot'], href=v['href']) for k, v in rank.items()]
TypeError: 'int' object is not subscriptable
2021-06-15 12:38:31,227 - ERROR - weibo.py[:179] - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 175, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 118, in updateJSON
    rank = {k: v for k, v in sorted(historyRank.items(), key=lambda item: item[1]['hot'], reverse=True)}
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 118, in <lambda>
    rank = {k: v for k, v in sorted(historyRank.items(), key=lambda item: item[1]['hot'], reverse=True)}
TypeError: 'int' object is not subscriptable
2021-06-15 12:38:45,362 - ERROR - weibo.py[:179] - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 175, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 118, in updateJSON
    rank = {k: v for k, v in sorted(historyRank.items(), key=lambda item: item[1]['hot'], reverse=True)}
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 118, in <lambda>
    rank = {k: v for k, v in sorted(historyRank.items(), key=lambda item: item[1]['hot'], reverse=True)}
TypeError: 'int' object is not subscriptable
2021-06-15 12:39:03,184 - ERROR - weibo.py[:178] - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 174, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 118, in updateJSON
    rank = {k: v for k, v in sorted(historyRank.items(), key=lambda item: item[1]['hot'], reverse=True)}
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 118, in <lambda>
    rank = {k: v for k, v in sorted(historyRank.items(), key=lambda item: item[1]['hot'], reverse=True)}
TypeError: 'int' object is not subscriptable
2021-06-15 12:47:39,527 - ERROR - weibo.py[:182] - unhashable type: 'slice'
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 178, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 120, in updateJSON
    rank = rank[0:5]
TypeError: unhashable type: 'slice'
2021-06-15 12:47:53,214 - ERROR - weibo.py[:182] - write() argument must be str, not list
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 178, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 124, in updateJSON
    save(filename, rank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 50, in save
    f.write(content)
TypeError: write() argument must be str, not list
2021-06-15 12:48:33,103 - ERROR - weibo.py[:181] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 177, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 108, in updateJSON
    historyRank = json.loads(load(filename))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-06-15 12:48:48,828 - ERROR - weibo.py[:181] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 177, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 108, in updateJSON
    historyRank = json.loads(load(filename))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-06-15 12:49:17,682 - ERROR - weibo.py[:181] - 'str' object has no attribute 'items'
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 178, in main
    rankMD = updateArchive(rankJSON)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 136, in updateArchive
    lines = [line.format(title=k, hot=v['hot'], href=v['href']) for k, v in rank.items()]
AttributeError: 'str' object has no attribute 'items'
2021-06-15 12:50:09,063 - ERROR - weibo.py[:180] - Expecting value: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 176, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 108, in updateJSON
    historyRank = json.loads(load(filename))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
2021-06-15 13:03:19,174 - ERROR - weibo.py[:181] - list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 177, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 120, in updateJSON
    rank = list(rank)[0, 5]
TypeError: list indices must be integers or slices, not tuple
2021-06-15 13:03:44,664 - ERROR - weibo.py[:181] - 'list' object has no attribute 'items'
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 178, in main
    rankMD = updateArchive(rankJSON)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 136, in updateArchive
    lines = [line.format(title=k, hot=v['hot'], href=v['href']) for k, v in rank.items()]
AttributeError: 'list' object has no attribute 'items'
2021-06-15 13:04:15,802 - ERROR - weibo.py[:181] - list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 177, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 112, in updateJSON
    historyRank[k]['hot'] = max(historyRank[k]['hot'], correntRank[k]['hot'])
TypeError: list indices must be integers or slices, not str
2021-06-15 13:21:07,487 - ERROR - weibo.py[:186] - [Errno 2] No such file or directory: './raw/20210615.json'
Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 182, in main
    rankJSON = updateJSON(correntRank)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 106, in updateJSON
    save(filename, {})
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 44, in save
    with open(filename, 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './raw/20210615.json'
2021-06-15 18:15:52,868 - ERROR - weibo.py[:197] - HTTPSConnectionPool(host='s.weibo.com', port=443): Max retries exceeded with url: /top/summary (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 366, in connect
    self._tunnel()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 904, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 503 Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s.weibo.com', port=443): Max retries exceeded with url: /top/summary (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 191, in main
    content = getHTML(BASE_URL + url)
  File "/Users/hamster/Desktop/weibo-hot-search-main/weibo.py", line 39, in getHTML
    response = requests.get(url, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='s.weibo.com', port=443): Max retries exceeded with url: /top/summary (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))
